# =============================================================================
# Ethio Nordic ERP - NGINX Main Configuration
# =============================================================================
# Main config file - includes the API Gateway config
# =============================================================================

worker_processes auto;
error_log C:/Users/hp/Desktop/Ethio-Nordic-ERP/logs/error.log warn;
pid C:/Users/hp/Desktop/Ethio-Nordic-ERP/logs/nginx.pid;

events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

http {
    include C:/nginx/nginx-1.30.3/conf/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    tcp_nopush on;
    tcp_nodelay on;

    # Include the API Gateway config
    include C:/Users/hp/Desktop/Ethio-Nordic-ERP/nginx.conf;
}
